export const actionTypes = {
  // add urls
  ADD_URL_REQUEST: "ADD_URL_REQUEST",
  ADD_URL_SUCCESS: "ADD_URL_SUCCESS",
  ADD_URL_FAILURE: "ADD_URL_FAILURE",
  // get urls
  GET_URLS_REQUEST: "GET_URLS_REQUEST",
  GET_URLS_SUCCESS: "GET_URLS_SUCCESS",
  GET_URLS_FAILURE: "GET_URLS_FAILURE",
};
